// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChassisList():Promise<void>;

export function GetChassisListByHttp():Promise<void>;
