// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChassisList() {
  return window['go']['Computer']['Chassis']['GetChassisList']();
}

export function GetChassisListByHttp() {
  return window['go']['Computer']['Chassis']['GetChassisListByHttp']();
}
