// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {Computer} from '../models';

export function GetCPUList():Promise<void>;

export function GetCpuInfo():Promise<Computer.CPUInfo>;

export function GetCpuJSONData():Promise<any>;

export function GetUsingCpuInfo():Promise<number>;
