// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUList() {
  return window['go']['Computer']['CPU']['GetCPUList']();
}

export function GetCpuInfo() {
  return window['go']['Computer']['CPU']['GetCpuInfo']();
}

export function GetCpuJSONData() {
  return window['go']['Computer']['CPU']['GetCpuJSONData']();
}

export function GetUsingCpuInfo() {
  return window['go']['Computer']['CPU']['GetUsingCpuInfo']();
}
