// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGPUByHttp() {
  return window['go']['Computer']['GPU']['GetGPUByHttp']();
}

export function GetGPUList() {
  return window['go']['Computer']['GPU']['GetGPUList']();
}
