// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHDDList():Promise<void>;

export function GetHDDListByHttp():Promise<void>;
