// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHDDList() {
  return window['go']['Computer']['HDD']['GetHDDList']();
}

export function GetHDDListByHttp() {
  return window['go']['Computer']['HDD']['GetHDDListByHttp']();
}
