// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPowerList():Promise<void>;

export function GetPowerListByHttp():Promise<void>;
