// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPowerList() {
  return window['go']['Computer']['Power']['GetPowerList']();
}

export function GetPowerListByHttp() {
  return window['go']['Computer']['Power']['GetPowerListByHttp']();
}
