// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRadiatorList():Promise<void>;

export function GetRadiatorListByHttp():Promise<void>;
