// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRadiatorList() {
  return window['go']['Computer']['Radiator']['GetRadiatorList']();
}

export function GetRadiatorListByHttp() {
  return window['go']['Computer']['Radiator']['GetRadiatorListByHttp']();
}
