// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRamList():Promise<void>;

export function GetRamListByHttp():Promise<void>;
