// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSSDList() {
  return window['go']['Computer']['SSD']['GetSSDList']();
}

export function GetSSDListByHttp() {
  return window['go']['Computer']['SSD']['GetSSDListByHttp']();
}
