// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSSDList():Promise<void>;

export function GetSSDListByHttp():Promise<void>;
