// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllInfo() {
  return window['go']['main']['App']['GetAllInfo']();
}

export function GetCpuInfo() {
  return window['go']['main']['App']['GetCpuInfo']();
}

export function GetMemInfo() {
  return window['go']['main']['App']['GetMemInfo']();
}

export function GetUsingCpuInfo() {
  return window['go']['main']['App']['GetUsingCpuInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
