// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {Global} from '../models';

export function ExportFile(arg1:string,arg2:string):Promise<boolean>;

export function ExportFile2(arg1:string,arg2:Global.PCHardwork):Promise<boolean>;

export function GetPath():Promise<string>;

export function GetSettingsJson():Promise<{[key: string]: string}>;

export function SetExportFileType(arg1:string):Promise<boolean>;

export function SetExportFileUrl():Promise<string>;
