// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCpuInfo() {
  return window['go']['main']['App']['GetCpuInfo']();
}

export function GetCpuJSONData() {
  return window['go']['main']['App']['GetCpuJSONData']();
}

export function GetPath() {
  return window['go']['main']['App']['GetPath']();
}

export function GetRamInfo() {
  return window['go']['main']['App']['GetRamInfo']();
}

export function GetUsingCpuInfo() {
  return window['go']['main']['App']['GetUsingCpuInfo']();
}

export function SetExportFileUrl() {
  return window['go']['main']['App']['SetExportFileUrl']();
}
