// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {Computer} from '../models';

export function GetCpuInfo():Promise<Computer.CPUInfo>;

export function GetCpuJSONData():Promise<any>;

export function GetPath():Promise<string>;

export function GetRamInfo():Promise<Computer.RamInfo>;

export function GetUsingCpuInfo():Promise<number>;

export function SetExportFileUrl():Promise<string>;
