// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCpuInfo() {
  return window['go']['main']['App']['GetCpuInfo']();
}

export function GetRamInfo() {
  return window['go']['main']['App']['GetRamInfo']();
}

export function GetUsingCpuInfo() {
  return window['go']['main']['App']['GetUsingCpuInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetExportFileUrl() {
  return window['go']['main']['App']['SetExportFileUrl']();
}
