// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCount(arg1:number):Promise<number>;

export function Greet(arg1:string):Promise<string>;
